#!/usr/bin/env python3.8

import argparse
import statuscheck

parser = argparse.ArgumentParser()
parser.add_argument('-v', '--version', action='version', version='%(prog)s 0.0')
parser.add_argument('-c', '--check', action='store_true', help='Check to ensure device is ready to make a connection')
#parser.add_argument('-s', '--scan', help='Scan airwaves for devices to connect to')
#parser.add_argument('-i', '--interactive', help='Run as interactive script')
args = parser.parse_args()

check = (args.check)
#scan = (args.scan).strip().lower()
#interactive = (args.interactive).strip().lower()

if check:
    statuscheck.main()
